Insights listing page
vegaprotocol/vega.xyz pull request #362
Opened 2022-11-25 15:40 UTC by goslingo

2022-12-01 22:16 UTC, pennyandrews requested changes
I'm not sure if this is supposed to be done done but I've made a suggested change the Arrington title and then the blurb is currently the same for the messari and arrington articles.

2022-12-01 22:16 UTC, pennyandrews commented on src/content/insights/0002-arrington-capital.md
> +title: 'Vega Protocol: The Space Race For Open Markets: Vega'
```suggestion
title: 'The Space Race For Open Markets: Vega'
```

2022-12-02 16:18 UTC, goslingo commented
@pennyandrews please review this again, it should be ready to go now - thanks!

2022-12-06 12:01 UTC, pennyandrews approved these changes

2022-12-06 12:07 UTC, merged